// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: switchrpc/switch.proto

package switchrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkResultTrackedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttemptId uint64 `protobuf:"varint,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"` // The attempt ID to be marked as tracked.
}

func (x *MarkResultTrackedRequest) Reset() {
	*x = MarkResultTrackedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkResultTrackedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkResultTrackedRequest) ProtoMessage() {}

func (x *MarkResultTrackedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkResultTrackedRequest.ProtoReflect.Descriptor instead.
func (*MarkResultTrackedRequest) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{0}
}

func (x *MarkResultTrackedRequest) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

type MarkResultTrackedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation succeeded.
}

func (x *MarkResultTrackedResponse) Reset() {
	*x = MarkResultTrackedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkResultTrackedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkResultTrackedResponse) ProtoMessage() {}

func (x *MarkResultTrackedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkResultTrackedResponse.ProtoReflect.Descriptor instead.
func (*MarkResultTrackedResponse) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{1}
}

func (x *MarkResultTrackedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchAttemptResultsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchAttemptResultsRequest) Reset() {
	*x = FetchAttemptResultsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAttemptResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttemptResultsRequest) ProtoMessage() {}

func (x *FetchAttemptResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttemptResultsRequest.ProtoReflect.Descriptor instead.
func (*FetchAttemptResultsRequest) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{2}
}

type FetchAttemptResultsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttemptResults []*FetchAttemptResultsResponse_AttemptResult `protobuf:"bytes,1,rep,name=attempt_results,json=attemptResults,proto3" json:"attempt_results,omitempty"`
}

func (x *FetchAttemptResultsResponse) Reset() {
	*x = FetchAttemptResultsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAttemptResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttemptResultsResponse) ProtoMessage() {}

func (x *FetchAttemptResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttemptResultsResponse.ProtoReflect.Descriptor instead.
func (*FetchAttemptResultsResponse) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{3}
}

func (x *FetchAttemptResultsResponse) GetAttemptResults() []*FetchAttemptResultsResponse_AttemptResult {
	if x != nil {
		return x.AttemptResults
	}
	return nil
}

type SendOnionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw onion packet to be sent across the network.
	OnionBlob []byte `protobuf:"bytes,1,opt,name=onion_blob,json=onionBlob,proto3" json:"onion_blob,omitempty"`
	// The first hop's public key where the onion will be sent.
	FirstHopPubkey []byte `protobuf:"bytes,2,opt,name=first_hop_pubkey,json=firstHopPubkey,proto3" json:"first_hop_pubkey,omitempty"`
	// The total amount in millisatoshis required to complete a payment over
	// this route. This value includes the cumulative fees at each hop. The HTLC
	// extended to the first-hop in the route will need to have at least this
	// many (milli)satoshis.
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// The absolute timelock or CLTV value that should be extended to the first
	// hop in the route. All other hops will decrement the time-lock as
	// described by the onion.
	Timelock uint32 `protobuf:"varint,4,opt,name=timelock,proto3" json:"timelock,omitempty"`
	// The payment hash associated with the HTLC. This is needed for tracking
	// and debugging purposes.
	PaymentHash []byte `protobuf:"bytes,5,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// The attempt ID uniquely identifying this payment attempt. The caller can
	// expect to track results for the payment via this attempt ID.
	AttemptId uint64 `protobuf:"varint,6,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
}

func (x *SendOnionRequest) Reset() {
	*x = SendOnionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOnionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnionRequest) ProtoMessage() {}

func (x *SendOnionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnionRequest.ProtoReflect.Descriptor instead.
func (*SendOnionRequest) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{4}
}

func (x *SendOnionRequest) GetOnionBlob() []byte {
	if x != nil {
		return x.OnionBlob
	}
	return nil
}

func (x *SendOnionRequest) GetFirstHopPubkey() []byte {
	if x != nil {
		return x.FirstHopPubkey
	}
	return nil
}

func (x *SendOnionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendOnionRequest) GetTimelock() uint32 {
	if x != nil {
		return x.Timelock
	}
	return 0
}

func (x *SendOnionRequest) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

func (x *SendOnionRequest) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

type SendOnionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates if the onion was successfully sent or not.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// In case of failure, this field will provide more information about the
	// error.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// A code representing the type of error that occurred. This can be used
	// to programmatically distinguish between different kinds of errors.
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *SendOnionResponse) Reset() {
	*x = SendOnionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOnionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnionResponse) ProtoMessage() {}

func (x *SendOnionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnionResponse.ProtoReflect.Descriptor instead.
func (*SendOnionResponse) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{5}
}

func (x *SendOnionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendOnionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SendOnionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type TrackOnionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The payment hash associated with the HTLC. This is needed for tracking
	// and debugging purposes.
	PaymentHash []byte `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// The attempt ID uniquely identifying this payment attempt. The caller can
	// expect to track results for the payment via this attempt ID.
	AttemptId uint64 `protobuf:"varint,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	// Optional: Session key used to generate the onion/sphinx packet.
	SessionKey []byte `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// Optional: Public keys of nodes along the route, used with session_key.
	HopPubkeys [][]byte `protobuf:"bytes,4,rep,name=hop_pubkeys,json=hopPubkeys,proto3" json:"hop_pubkeys,omitempty"`
	// Optional: list of shared secrets for deobfuscating errors server side.
	// If not included, then it will be the caller's responsibility to decrypt
	// any errors from the SendOnion attempt.
	SharedSecrets [][]byte `protobuf:"bytes,5,rep,name=shared_secrets,json=sharedSecrets,proto3" json:"shared_secrets,omitempty"`
}

func (x *TrackOnionRequest) Reset() {
	*x = TrackOnionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackOnionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOnionRequest) ProtoMessage() {}

func (x *TrackOnionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOnionRequest.ProtoReflect.Descriptor instead.
func (*TrackOnionRequest) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{6}
}

func (x *TrackOnionRequest) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

func (x *TrackOnionRequest) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *TrackOnionRequest) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *TrackOnionRequest) GetHopPubkeys() [][]byte {
	if x != nil {
		return x.HopPubkeys
	}
	return nil
}

func (x *TrackOnionRequest) GetSharedSecrets() [][]byte {
	if x != nil {
		return x.SharedSecrets
	}
	return nil
}

type TrackOnionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates if the onion was successfully sent or not.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// The preimage obtained by making the payment.
	Preimage []byte `protobuf:"bytes,2,opt,name=preimage,proto3" json:"preimage,omitempty"`
	// In case of failure, this field will provide more information about the
	// error.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// If the caller provides no means to decrypt the error then we'll defer
	// error decryption on the server and return the encrypted error blob.
	EncryptedError []byte `protobuf:"bytes,4,opt,name=encrypted_error,json=encryptedError,proto3" json:"encrypted_error,omitempty"`
}

func (x *TrackOnionResponse) Reset() {
	*x = TrackOnionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackOnionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOnionResponse) ProtoMessage() {}

func (x *TrackOnionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOnionResponse.ProtoReflect.Descriptor instead.
func (*TrackOnionResponse) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{7}
}

func (x *TrackOnionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackOnionResponse) GetPreimage() []byte {
	if x != nil {
		return x.Preimage
	}
	return nil
}

func (x *TrackOnionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TrackOnionResponse) GetEncryptedError() []byte {
	if x != nil {
		return x.EncryptedError
	}
	return nil
}

type FetchAttemptResultsResponse_AttemptResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttemptId     uint64 `protobuf:"varint,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ResultDetails string `protobuf:"bytes,2,opt,name=result_details,json=resultDetails,proto3" json:"result_details,omitempty"` // Simplified result details.
}

func (x *FetchAttemptResultsResponse_AttemptResult) Reset() {
	*x = FetchAttemptResultsResponse_AttemptResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_switchrpc_switch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAttemptResultsResponse_AttemptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttemptResultsResponse_AttemptResult) ProtoMessage() {}

func (x *FetchAttemptResultsResponse_AttemptResult) ProtoReflect() protoreflect.Message {
	mi := &file_switchrpc_switch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttemptResultsResponse_AttemptResult.ProtoReflect.Descriptor instead.
func (*FetchAttemptResultsResponse_AttemptResult) Descriptor() ([]byte, []int) {
	return file_switchrpc_switch_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FetchAttemptResultsResponse_AttemptResult) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *FetchAttemptResultsResponse_AttemptResult) GetResultDetails() string {
	if x != nil {
		return x.ResultDetails
	}
	return ""
}

var File_switchrpc_switch_proto protoreflect.FileDescriptor

var file_switchrpc_switch_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x72, 0x70, 0x63, 0x22, 0x39, 0x0a, 0x18, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x22, 0x35,
	0x0a, 0x19, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x1b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x73,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74,
	0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x0e, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x1a, 0x55, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x6f, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x28, 0x0a,
	0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x68, 0x6f, 0x70, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x48, 0x6f,
	0x70, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x22, 0x71, 0x0a,
	0x11, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0xbe, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61,
	0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x6f, 0x70,
	0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a,
	0x68, 0x6f, 0x70, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x22, 0x98, 0x01, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4f, 0x6e, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x65, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xe1, 0x02, 0x0a,
	0x06, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x4f,
	0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e,
	0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4f,
	0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4f, 0x6e, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x4d, 0x61,
	0x72, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x12,
	0x23, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x72, 0x6b,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x13, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x25, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x69, 0x6e, 0x67, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x6c, 0x6e, 0x64, 0x2f, 0x6c, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_switchrpc_switch_proto_rawDescOnce sync.Once
	file_switchrpc_switch_proto_rawDescData = file_switchrpc_switch_proto_rawDesc
)

func file_switchrpc_switch_proto_rawDescGZIP() []byte {
	file_switchrpc_switch_proto_rawDescOnce.Do(func() {
		file_switchrpc_switch_proto_rawDescData = protoimpl.X.CompressGZIP(file_switchrpc_switch_proto_rawDescData)
	})
	return file_switchrpc_switch_proto_rawDescData
}

var file_switchrpc_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_switchrpc_switch_proto_goTypes = []interface{}{
	(*MarkResultTrackedRequest)(nil),                  // 0: switchrpc.MarkResultTrackedRequest
	(*MarkResultTrackedResponse)(nil),                 // 1: switchrpc.MarkResultTrackedResponse
	(*FetchAttemptResultsRequest)(nil),                // 2: switchrpc.FetchAttemptResultsRequest
	(*FetchAttemptResultsResponse)(nil),               // 3: switchrpc.FetchAttemptResultsResponse
	(*SendOnionRequest)(nil),                          // 4: switchrpc.SendOnionRequest
	(*SendOnionResponse)(nil),                         // 5: switchrpc.SendOnionResponse
	(*TrackOnionRequest)(nil),                         // 6: switchrpc.TrackOnionRequest
	(*TrackOnionResponse)(nil),                        // 7: switchrpc.TrackOnionResponse
	(*FetchAttemptResultsResponse_AttemptResult)(nil), // 8: switchrpc.FetchAttemptResultsResponse.AttemptResult
}
var file_switchrpc_switch_proto_depIdxs = []int32{
	8, // 0: switchrpc.FetchAttemptResultsResponse.attempt_results:type_name -> switchrpc.FetchAttemptResultsResponse.AttemptResult
	4, // 1: switchrpc.Switch.SendOnion:input_type -> switchrpc.SendOnionRequest
	6, // 2: switchrpc.Switch.TrackOnion:input_type -> switchrpc.TrackOnionRequest
	0, // 3: switchrpc.Switch.MarkResultTracked:input_type -> switchrpc.MarkResultTrackedRequest
	2, // 4: switchrpc.Switch.FetchAttemptResults:input_type -> switchrpc.FetchAttemptResultsRequest
	5, // 5: switchrpc.Switch.SendOnion:output_type -> switchrpc.SendOnionResponse
	7, // 6: switchrpc.Switch.TrackOnion:output_type -> switchrpc.TrackOnionResponse
	1, // 7: switchrpc.Switch.MarkResultTracked:output_type -> switchrpc.MarkResultTrackedResponse
	3, // 8: switchrpc.Switch.FetchAttemptResults:output_type -> switchrpc.FetchAttemptResultsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_switchrpc_switch_proto_init() }
func file_switchrpc_switch_proto_init() {
	if File_switchrpc_switch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_switchrpc_switch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkResultTrackedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkResultTrackedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAttemptResultsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAttemptResultsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOnionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOnionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackOnionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackOnionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_switchrpc_switch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAttemptResultsResponse_AttemptResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_switchrpc_switch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_switchrpc_switch_proto_goTypes,
		DependencyIndexes: file_switchrpc_switch_proto_depIdxs,
		MessageInfos:      file_switchrpc_switch_proto_msgTypes,
	}.Build()
	File_switchrpc_switch_proto = out.File
	file_switchrpc_switch_proto_rawDesc = nil
	file_switchrpc_switch_proto_goTypes = nil
	file_switchrpc_switch_proto_depIdxs = nil
}
